apiVersion: v2
name: devx-helloworld-springboot-test-kp3y0
description: Chart for creating devx-helloworld-springboot-test-kp3y0 and ingress mapping our Flexport EKS clusters

type: application
version: 0.1.0
